### ISSUE TITLE
Simpler example of multi-arity function

### ISSUE THREAD

**Issue by Robsteranium** [clojurebridge-berlin/curriculum#20]
As per #11, cc @vsmart.

I agree that the `total-with-tip` function isn't immediately obvious and it ought to be simpler to understand.

Perhaps it ought to call `total-bill`? Or maybe we should avoid giving mathematical examples altogether?

**Comment by Realtin** [comment]
I think the main problem with this function is that for non-americans it is super confusing on why the tax has to be added to get a total, since we are used to have prices that already include tax. 

If we could find a problem that is more common for europe then the math behind it wouldn't be a problem  ( I suspect )

**Comment by Robsteranium** [comment]
Yeah that makes sense.

PR #23 removes these functions anyway. I'll close the issue now. Please re-open it if you think we need to do something different.
